version: '3'
services:
  wordpress:
    image: wordpress:6.5.3
    ports:
      - 8888:80
    restart: always
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
  composer:
    image: composer:latest
    volumes:
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./vendor:/app/vendor/
    command: install
  db:
    image: mysql:8.4.0 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - 3306:3306 # change ip if required
    volumes:
      - ./prod/sql:/docker-entrypoint-initdb.d
      # - ./app/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "wordpress"
      MYSQL_ROOT_HOST: '%'
    # command: [ "mysqld", "--mysql-native-password=ON" ]
    command: --mysql-native-password=ON
    # command: --default-authentication-plugin=mysql_native_password
    # pma:
    #   image: phpmyadmin/phpmyadmin
    #   restart: always
    #   environment:
    #     # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
    #     PMA_HOST: db
    #     PMA_PORT: 3306
    #     MYSQL_ROOT_PASSWORD: "wordpress"
    #     UPLOAD_LIMIT: 50M
    #   ports:
    #     - 8080:80
    #   links:
    #     - db:db

volumes:
  db_data:
