version: '3'
services: 
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - 3306:3306
    volumes:
      # - ./init-db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
      - .mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "wordpress"

volumes:
  db_data: